### ISSUE TITLE
New FFMPEG Pipeline: CUVID doesn't support 10-bit H.264

### ISSUE THREAD

**Issue by dude22072** [chrisbenincasa/tunarr#1003]
As the title says, h264_cuvid doesn't support decoding 10-bit H.264 video. This results in a "This channel is experiencing technical difficulties" screen for the duration of the scheduled item. When enabling FFMPEG logging this is at the end of the log for the item, informing of the lack of support:
```
[h264_cuvid @ 0x3717c80] Bit depth 10 is not supported.
[vist#0:0/h264 @ 0x3457cc0] [dec:h264_cuvid @ 0x3717200] Error while opening decoder: Invalid argument
[fc#0 @ 0x322c340] Error binding an input stream to complex filtergraph input scale_cuda:default.
Error binding filtergraph inputs/outputs: Invalid argument
```
10-bit H.264 works fine under the existing software decode -> hardware encode pipeline, so the solution would be to have the new pipeline fall back to software decoding for unsupported inputs

**Comment by chrisbenincasa** [comment]
Can you provide the full ffmpeg command for the failing stream? Curious because we already attempt to use software decoding for h264>=10 bit: https://github.com/chrisbenincasa/tunarr/blob/dev/server/src/ffmpeg/builder/capabilities/NvidiaHardwareCapabilities.ts#L43 and here https://github.com/chrisbenincasa/tunarr/blob/dev/server/src/ffmpeg/builder/capabilities/NvidiaHardwareCapabilities.ts#L43

So, I’m wondering whether our detection of the incoming pixel format is off. The full ffmpeg may help determine that. I should also add some logging for the beginning stream state before passing it off to the pipeline builder.

**Comment by dude22072** [comment]
From the ffmpeg-report-test log: 
`/usr/bin/ffmpeg -threads 4 -nostdin -hide_banner -nostats -loglevel error -fflags +genpts+discardcorrupt+igndts -hwaccel cuda -ss 542.655s -c:v h264_cuvid -hwaccel_output_format cuda -readrate 1.0 -readrate_initial_burst 45 -i "/MediaLinks/TV Shows/Sailor Moon (1992) {imdb-tt0103369}/Season 01/Sailor Moon (1992) - S01E01 - 001 - The Crybaby Usagis Beautiful Transformation [DVD v2][10bit][x264][FLAC 2.0][JA+EN].mkv" -filter_complex "[0:0]scale_cuda=1920:1080:format=nv12:force_original_aspect_ratio=decrease,setsar=1,hwdownload,format=nv12,pad=1920:1080:-1:-1:color=black,hwupload_cuda[v];[0:1]aresample=async=1:first_pts=0,apad=whole_dur=908171ms[a];[v]scale_cuda=format=yuv420p[vpf]" -map "[vpf]" -map "[a]" -muxdelay 0 -muxpreload 0 -flags cgop -movflags +faststart -t 908171ms -video_track_timescale 90000 -b:v 10000k -maxrate:v 10000k -bufsize:v 1000k -c:v h264_nvenc -c:a aac -b:a 192k -maxrate:a 192k -bufsize:a 50k -ar 48k -g 96 -keyint_min 96 -force_key_frames "expr:gte(t,n_forced*4)" -f hls -hls_time 4 -hls_list_size 0 -segment_list_flags +live -hls_segment_type mpegts -hls_segment_filename "streams/stream_93d6d42d-0409-4c08-9ba9-0b37a4728af9/data%06d.ts" -hls_base_url /stream/channels/93d6d42d-0409-4c08-9ba9-0b37a4728af9/hls/ -hls_flags program_date_time+append_list+omit_endlist+independent_segments streams/stream_93d6d42d-0409-4c08-9ba9-0b37a4728af9/stream.m3u8
`

also the video stream that FFMPEG sees in the file: 
` Stream #0:0(jpn): Video: h264, yuv420p10le(progressive), 768x576, SAR 1:1 DAR 4:3, 24 fps, 24 tbr, 1k tbn (default)
`

**Comment by chrisbenincasa** [comment]
Nice, thanks. Judging from the other bug you opened, I'm gonna assume your media source is Plex. If so, I think the issue here is that Plex does not give us the pixel format (or bit depth) of the video stream in its metadata, which is what Tunarr uses to derive info. I think the fix here is to actually extract that info (and possibly all of the needed info) using ffprobe instead.
