### ISSUE TITLE
RUNNING LIST: Implement upstream features added since fork

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#14]
https://github.com/vexorian/dizquetv/compare/6898b9f31d6641297754c5e2e1f5d58f624af7e7...869987bdb1a5aed1dbfdba5ab48329e1dc18410b

- [ ] Interlude support (https://github.com/vexorian/dizquetv/commit/66804fe26c7ee1797f2bf38790b424c8d46ede16 and others)
- [x] Look into mpeg2video fix here: https://github.com/vexorian/dizquetv/commit/56a4f3fdd824d725e1c5f3128480af177ccc4fcb - DONE bf3b076ae141a46b98964ae485edb95616d45483
- [ ] Use median to decide which filler to play https://github.com/vexorian/dizquetv/commit/ad1302aae418311701a2e6f153d8b145810c13be
- [ ] Look into changes here: https://github.com/vexorian/dizquetv/commit/35b828ed63847b07612f483bc5e3699589842be4
- [x] Ensure we're showing song title in XMLTV:https://github.com/vexorian/dizquetv/commit/88f03638fbbc53e4d0fdc92f56b6dbeba0a3761b

**Comment by chrisbenincasa** [comment]
Here's a rough list of commits that have been added upstream since I forked a few months back: https://github.com/vexorian/dizquetv/compare/1.4.5...main

**Comment by chrisbenincasa** [comment]
techinically we're correctly showing track titles in the xmltv - we could probably have more details in there though

![image](https://github.com/chrisbenincasa/tunarr/assets/1640671/e0716cbb-6e64-4579-a150-0eed0ad09faa)

**Comment by jasongdove** [comment]
FYI you probably don't want these changes as-is https://github.com/chrisbenincasa/tunarr/commit/bf3b076ae141a46b98964ae485edb95616d45483

For the `stillimage` tune, I think it would make more sense to explicitly enable for only those encoders known to support it. The upside of the tune as written is that it optimizes the (brief) loading screen, while the downside is that the stream won't start at all if the encoder doesn't support that specific tune. Also, there is some duplication: https://github.com/chrisbenincasa/tunarr/blob/bf3b076ae141a46b98964ae485edb95616d45483/server/src/ffmpeg.ts#L424-L430

https://github.com/chrisbenincasa/tunarr/blob/bf3b076ae141a46b98964ae485edb95616d45483/server/src/ffmpeg.ts#L671-L673

For the "`mpeg2video` fix" which replaced `-b:v` (target video bitrate) with `-crf` (constant quality mode) for all encoders except `mpeg2video` - it's kind of a similar story since many encoders don't support `-crf`, though at least they seem to ignore it rather than failing altogether. This introduced a *massive* quality loss for everything except `mpeg2video`.

My guess is that DTV testing may be limited to `mpeg2video` and `libx264`, in which case these recent changes wouldn't really affect anything, or might actually improve things, but for anyone using hardware encoding they have not been well received.

**Comment by chrisbenincasa** [comment]
Closing this out for now - don't think it is worthwhile to DI any of these changes at the moment,
