### ISSUE TITLE
Use mui-x date picker on TV Guide page

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/tunarr#274]
We use this in the slot editor page (and I think some other places) and it's really nice. We should replace the day-by-day dropdown on the TV guide with it.

**Comment by markdavella** [comment]
Yea, the mui-x date picker is great because its themed and support dark mode.

We should also update the guide page so it shows content beyond the EPG setting limit.  Right now mine is set to 12 hours and the Guide doesn't show anything beyond 12 hours.  I imagine it should loop once it hits the EPG limit

**Comment by chrisbenincasa** [comment]
Yea we may want to separate the XMLTV generation from the guide stuff. That way we can honor the setting for EPG hours but still generate as much guide on the backend as we want.

**Comment by chrisbenincasa** [comment]
Hmmm actually looping isn't quite right if the channel's duration is > EPG limit. Some channels are scheduled out for days/weeks (e.g. with time slots). If we can figure out a way to quickly build the guide on the fly that might be useful. I will do some tests in a separate issue
