### ISSUE TITLE
[Bug]: Windows Edge SyntaxError

### ISSUE THREAD

**Issue by AnyWays655** [chrisbenincasa/tunarr#469]
### What happened?

When running the Windows Edge this occurs and does not install, the terminal only appears briefly with this before shutting down.

![image](https://github.com/chrisbenincasa/tunarr/assets/12373967/bd934cd2-3620-433f-a3ab-6cda58c6dd04)

### Version

edge build June 2, 19:05

**Comment by chrisbenincasa** [comment]
Hey thanks for the report! We admittedly have had a big lack of testing on windows simply due to hardware constraints. I should be able to take a look at this issue this week though. 

Definitely a strange error to see though, considering we use an identical bundling setup for the windows build and only the executable it gets injected into is different.

**Comment by chrisbenincasa** [comment]
I believe this should be solved in #470, which I will submit shortly.

The main difference now is that our standalone binary will ship in a .zip that contains some extra dependencies that we have to bundle alongside the app (specifically bindings to interact with sqlite). 

![image](https://github.com/chrisbenincasa/tunarr/assets/1640671/900f56c8-1468-4ca7-b6a6-36e425d2e8b9)
