### ISSUE TITLE
[BUG] Adding too much media to a channel breaks scrolling and saving.

### ISSUE THREAD

**Issue by clrksml** [chrisbenincasa/tunarr#638]
### What happened?

Adding to much media to a channel breaks scrolling and saving.

OS: UnRaid 6.11.5
docker: binhex-plexpass:latest
docker: tunarr:edge-nvidia

1462 programs 25 days
![image](https://github.com/user-attachments/assets/6171ed01-fb00-4a97-a2a7-d8b6334637f8)

If I scroll error is thrown. 
![image](https://github.com/user-attachments/assets/4f803867-e473-48f8-9b80-1eca039405cc)

If I save,
> Error saving programs. Zodios: Invalid Body parameter 'body'

### Version

0.2.0

### What browser did you experience the the problem on?

Firefox (128.0)

### What operating system are you using?

Windows (NT 10.0)

### Relevant log output

```shell
BYe@http://192.168.1.2:8000/web/assets/index-52391a51.js:384:74848
xA@http://192.168.1.2:8000/web/assets/index-52391a51.js:62:19550
CU@http://192.168.1.2:8000/web/assets/index-52391a51.js:64:44101
SU@http://192.168.1.2:8000/web/assets/index-52391a51.js:64:39821
Ite@http://192.168.1.2:8000/web/assets/index-52391a51.js:64:39747
Rb@http://192.168.1.2:8000/web/assets/index-52391a51.js:64:39596
eR@http://192.168.1.2:8000/web/assets/index-52391a51.js:64:35959
yU@http://192.168.1.2:8000/web/assets/index-52391a51.js:64:34906
T@http://192.168.1.2:8000/web/assets/index-52391a51.js:49:1546
M@http://192.168.1.2:8000/web/assets/index-52391a51.js:49:1909
```

**Comment by chrisbenincasa** [comment]
Looks like we have 2 errors here: both definitely related to some metadata that Tunarr expects (possibly erroneously).  

We've seen the error on submission a bunch of times. That request never hits the server because it doesn't pass schema validation. If you open up your browser developer tools there should be more details about the error which will help us diagnose which field(s) are causing the issue. 

As for the scrolling: there might be more context in the browser log as well. I haven't seen that one before, but it's almost definitely either missing or malformed metadata from the programs you're adding which we should be able to handle gracefully.

**Comment by trevren11** [comment]
Added some context to https://github.com/chrisbenincasa/tunarr/issues/511#issuecomment-2254245561

**Comment by chrisbenincasa** [comment]
This should be fixed now. LMK if it's still an issue for you!
