### ISSUE TITLE
/Users/brad/Downloads/tunarr-macos-x64-2/macos-entrypoint.sh: line 3: /Users/brad/bin/node: No such file or directory /Users/brad/Downloads/tunarr-macos-x64-2/macos-entrypoint.sh: line 3: exec: /Users/brad/bin/node: cannot execute: No such file or directory  Saving session... ...copying shared history... ...saving history...truncating history files... ...completed.  [Process completed] [Bug]: 

### ISSUE THREAD

**Issue by RealBradCool** [chrisbenincasa/tunarr#667]
### Contact Details

starcodebrad2023@outlook.com is my email

### What happened?

A bug happened! and it crashes on load.

### Version

0.5.2

### What browser did you experience the the problem on?

I just started it and does not want to open the macos-entrypoint sh file

### What operating system are you using?

Mac

### Relevant log output

```shell
/Users/brad/Downloads/tunarr-macos-x64-2/macos-entrypoint.sh: line 3: /Users/brad/bin/node: No such file or directory
/Users/brad/Downloads/tunarr-macos-x64-2/macos-entrypoint.sh: line 3: exec: /Users/brad/bin/node: cannot execute: No such file or directory

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by chrisbenincasa** [comment]
The script is intended to be run from within the `tunarr-macos-x64` directory, since it relatively references the version of node that is packaged alongside. It may be good for us to make the script more resilient to that, but in the meantime if you run that script from within the unzipped app directory it should work (I just confirmed this)

**Comment by chrisbenincasa** [comment]
I have opened #668 to track improving this script
