### ISSUE TITLE
Flex added after clearing schedule

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#745]
Repro steps:
On a channcel with a schedule do the following:
- Click Tools > Clear Schedule
  - You will notice the schedule is cleared entirely
- Click Save
  - You will notice Flex time gets added as a replacement

I would expect there to just be no content in the channel, flex or otherwise

<img width="1478" alt="image" src="https://github.com/user-attachments/assets/960edce9-78c8-4e1d-9154-1ca01a81dadd">

**Comment by chrisbenincasa** [comment]
Yea this is a weird side effect of the server trying to ensure that there is always at least one item in the channel's lineup, since there are a bunch of scheduling algorithms that rely on that assumption. I think you're right that it's really weird, we just need to be careful about removing the logic that always ensures a channel is non-empty because there will be a lot of other places affected
