### ISSUE TITLE
Add the ability to weight and balance shows

### ISSUE THREAD

**Issue by SergeantPanda** [chrisbenincasa/tunarr#767]
One thing that I see missing from dizque is the ability to weight and balance shows so that when block shuffling is done, the end of the rotation isn't all just one or two shows (that have more episodes). The attached picture is for reference to what I'm talking about from dizque.
![image](https://github.com/user-attachments/assets/923b6082-5eba-4f79-9a3b-3082b391e125)

**Comment by chrisbenincasa** [comment]
I can look into this, but perhaps I'm doing something wrong in DTV while trying to understand how this works. 

I have a simple channel I'm testing with - it has 3 different shows in it. I create a block shuffle of length 3. Like you said, there's a "tail" of shows at the end. But then, if I click "balance" shows, it completely undoes the block scheduling.

**Comment by SergeantPanda** [comment]
Yeah, so to make it easy to duplicate, add two shows one show that has many more episodes. Do a block shuffle, you should see that one show has a tail. If you do a 'balance' it will adjusts the weights and then when you do the block shuffle again, it should end at about the same place. It isn't perfect but it does help so you don't end up with 3 seasons of just one show playing at the end.

**Comment by SergeantPanda** [comment]
Honestly I think what would make the most sense is an option to be able to loop a show when it runs out of episodes. So that you can keep the set block shuffle of say 3 episodes and then it switches but when an episode runs out it starts back at season 1 episode 1.

**Comment by SergeantPanda** [comment]
That would make it easier to code and achieve what the end goal is better imo.

**Comment by chrisbenincasa** [comment]
I think https://github.com/chrisbenincasa/tunarr/pull/802 should have some improvements that will help!

**Comment by SergeantPanda** [comment]
Yep that will work. Much better than what was there before. I am curious though, what happens at the end of the list, does it start over at the top or would it continue with where each show left off?

**Comment by chrisbenincasa** [comment]
Ah yes so that's a good point. Currently it's simplistic- it'll just loop to the top. Not ideal I suppose but the first cut just really optimized for perfect block counts

I guess a more natural schedule technique would be to expand the schedule out so that the final blocks for each group are the "end" and looping would restart all shows at their beginning. This is slightly more complex but doable. I think the method would be the find the least common multiple between the counts for the number of blocks needed for 1 "cycle" of each show. 

What might make this a little easier is the property that the number of blocks needed for a cycle is always equal to the number of programs in each show. So I think if we found the LCM(N1, N2, ...Nm) where N is the number of programs in each show, we'd know how many blocks to make for each and have a perfectly cyclic block schedule. 

The only downside I can think of is that this can potentially make schedules reallllyyyy long, but we can test it out and see.

**Comment by chrisbenincasa** [comment]
I guess we could try to trim further for shows that have an even number of episodes and we're scheduling with an even block size, so like 20 episodes takes 20 two-ep blocks to repeat but only 10 four-ep blocks. Unclear how much that'll affect the schedule expansion but I'll see.

**Comment by SergeantPanda** [comment]
Yeah that makes sense to me as well. I could see either working

**Comment by chrisbenincasa** [comment]
Latest release has the experimental 'perfect sync' option using the method I described above. Right now it's disabled if it thinks it'll make the schedule too huge - this tends to happens if there are a lot of unique shows in the channel. It still needs some more touch up work (like options around what to do with movie blocks) but for shows / custom shows it works pretty well.

**Comment by chrisbenincasa** [comment]
Closing this out after our discussion in the discord. I've kept around balance shows for now, but the recommended approach in the future is either:

1. block shuffle + loop short blocks (which is now the default)
2. block shuffle w/ perfect loop on, if possible for a particular channel
