### ISSUE TITLE
Some shows sometimes do not show up when using Time/Random Slots. and some other Slots things.  

### ISSUE THREAD

**Issue by sloothy420** [chrisbenincasa/tunarr#825]
Version 0.12.2

All shows do not show up in the drop down  when choosing time slots. I'm not sure how to replicate this, as its kind of finicky and i find it usually happens right after initially adding the media to the channel. But it will only show some of the shows that i had added when opening the dropdown to choose shows. Saving the lineup as is and then going back to the channels page and then trying again a few times ends up having the shows pop up but cant get them to show every time. consistently. 

A couple of other things: could it be possible for the drop down, when displaying all the shows in a channel, could always order them in alphabetical? It could help with channels with a lot of shows to stay organized. 

I believe there is already a ticket open for this, but i could be wrong, but after getting your random slots ready and clicking save, it updates the xml but trying to go back to programming says there are unsaved changes. 

Final thought: Per our conversation in discord about a new tool as this would fit nicely either in time slots or a future tool but having it already populate the shows on the page. For example, as it is now, i have to add a slot and then choose a show, but having an option to auto populate the list based on the shows already in the lineup would save a lot of time and already have all the tools at your disposal to get rid of a show you dont want or fiddle with their times and play order etc etc.

**Comment by chrisbenincasa** [comment]
For the first part: I think this is because these things use season/show data that we persist to the DB, which happens asynchronously when adding new programs (because it potentially creates a _ton_ of DB activity). This is something we pushed off the sync path because it was making channel lineup updates suuuuuper slow for some people, but it's something I'm willing to revisit -- either with DB changes or with a UI indicator saying that the channel is still being updated, or something. 

> A couple of other things: could it be possible for the drop down, when displaying all the shows in a channel, could always order them in alphabetical? It could help with channels with a lot of shows to stay organized.

yes, I'll open a separate issue for this.

> I believe there is already a ticket open for this, but i could be wrong, but after getting your random slots ready and clicking save, it updates the xml but trying to go back to programming says there are unsaved changes.

I think I fixed this on the time slots page, but perhaps I forgot the random slots page... these really need to start sharing some code. I'll check it out.

> auto populate the list based on the shows already in the lineup

I like this idea - wanna open another separate issue for it? I think the only "complicated" thing we'd need to figure out is predicting the length of time for the slot. Shouldn't be too hard though!

**Comment by chrisbenincasa** [comment]
Good call on the scheduling bug. It should be fixed with ac3f84a11ad38b46374760ed2af22e9930d85b20

**Comment by chrisbenincasa** [comment]
Have an update here: this sorta forced my hand on something I've been meaning to do for a while, which is start to replace more of the DB framework we use for some parts of the app with another library that is lower level but much faster. Because the previous library was slow for massive amounts of items, I deferred some work when updating schedules (namely saving program hierarchies, shows/seasons/etc) to be asynchronous. However this causes the weird scenario like you're seeing where these groupings aren't immediately available. 

Happy to report I have an initial version with the new database library working to do all of this work upfront and it's...way faster than I was expecting. Going to be doing some more testing in the coming days before I'll have a release though.
