### ISSUE TITLE
Channel name changes not propagating to lineups API

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#84]
I changed the names for channels 2 and 3 and they display correctly on the channels page:
<img width="1391" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/f8291aab-df0d-4ba5-b8ae-943456d2906a">

However, if I navigate to the guide page, I can see the old names:
<img width="711" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/a14889d4-4ed7-44e1-8aea-7322b0058d88">

I confirmed that these are both being served up by the API, so it doesn't look like a state issue.  I also went incognito and refetched the queries so it doesn't seem like a React Query cache issue.

Confirmed data is in the DB correctly:
<img width="568" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/54190a26-1407-4d7e-8b8e-0ad1e841b31b">

Maybe some DB cache issue?

**Comment by chrisbenincasa** [comment]
Yes this is because the server caches the guide it bills that is used for the xmltv file. It does this along with a few details about the channel including name. 

The caching is from the legacy behavior. It makes sense why it was done, I think. At least for the programs (stable schedule and reducing compute). I think it would be ok to not cache the channel details though. 

We should also make it so that any updates to channel fields that are in the xmltv file cause the server to regenerate that file
